name: CI/CD for Backend and Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies for Backend
      working-directory: /e/projects/Tamini/back
      run: npm install

    - name: Run tests for Backend
      working-directory: /e/projects/Tamini/back
      run: npm test

    - name: Build Docker image for Backend
      working-directory: /e/projects/Tamini/back
      run: docker build -t backend-app .

  build-and-test-frontend:
    runs-on: ubuntu-latest
    needs: build-and-test-backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies for Frontend
      working-directory: /e/projects/Tamini/front
      run: npm install

    - name: Run tests for Frontend
      working-directory: /e/projects/Tamini/front
      run: npm test

    - name: Build Docker image for Frontend
      working-directory: /e/projects/Tamini/front
      run: docker build -t frontend-app .

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-test-backend, build-and-test-frontend]

    steps:
    - name: Deploy Backend to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r /e/projects/Tamini/back $SSH_USER@$SSH_HOST:/home/digital/
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
          cd /home/digital/back
          docker build -t backend-app .
          docker stop backend-app || true
          docker rm backend-app || true
          docker run -d -p 3001:3001 --name backend-app backend-app
        EOF

    - name: Deploy Frontend to server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -r /e/projects/Tamini/front $SSH_USER@$SSH_HOST:/home/digital/
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
          cd /home/digital/front
          docker build -t frontend-app .
          docker stop frontend-app || true
          docker rm frontend-app || true
          docker run -d -p 3000:3000 --name frontend-app frontend-app
        EOF
