services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"  # فقط دسترسی لوکال
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always
    networks:
      - mynetwork

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "127.0.0.1:8081:8081"  # فقط دسترسی لوکال
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    restart: always
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3001:3001"  # فقط دسترسی لوکال
    volumes:
      - ./backend:/usr/src/app  # فقط فایل‌های ضروری را mount کنید
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/tamini
      - PORT=3001
    depends_on:
      - mongo 
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"  # فقط دسترسی لوکال
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - API_URL=http://backend:3001
    restart: always
    networks:
      - mynetwork

volumes:
  mongo_data:

networks:
  mynetwork:
    driver: bridge
