name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  backend:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install backend dependencies
      run: |
        cd backend
        npm install

    - name: Run backend tests
      run: |
        cd backend
        npm test

    - name: Build backend
      run: |
        cd backend
        npm run build

    - name: Deploy backend
      run: echo "Deploying backend..."  # Replace with actual deployment steps

  frontend:
    runs-on: ubuntu-latest
    needs: backend

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install

    - name: Run frontend tests
      run: |
        cd frontend
        npm test

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Deploy frontend
      run: echo "Deploying frontend..."  # Replace with actual deployment steps
